### ISSUE TITLE
list index out of range when parsing 20th march

### ISSUE THREAD

**Issue by saroup** [alvinwan/timefhuman#10] opened 2019-10-09 15:02 UTC
timefhuman('20th march')
gives : list index out of range
also when is try with 'march 20th'
it gives : 'DayToken' object has no attribute 'isnumeric'

**Comment by igornfaustino** [comment] 2019-11-04 19:40
I think part of the problem is the "th" suffix. The library works fine with the string "march 20".
The other suffix works fines ("st", "nd", "rd") just the "th" one cause this kind of bug

**Comment by alvinwan** [comment] 2019-11-22 00:32
Thank you for reporting @saroup! @igornfaustino was kind enough to introduce a PR fixing issue. #11 has now been merged.

**Closed by alvinwan** 2019-11-22 00:33 UTC
